/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vista;

/**
 *
 * @author Diurno
 */
public class MenuCompraProvedor extends javax.swing.JFrame {

    /** Creates new form VentanaPrincipal */
    public MenuCompraProvedor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnActPrecio = new javax.swing.JButton();
        btnConsultarCompra = new javax.swing.JButton();
        btnEliminarProvedor = new javax.swing.JButton();
        btnModCompra = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setLabel("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setText("Menú Compras de Provedores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 270, 30));
        jLabel1.getAccessibleContext().setAccessibleName("");

        btnActPrecio.setText("Actualizar Precio");
        btnActPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(btnActPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        btnConsultarCompra.setText("Consultar Compra");
        btnConsultarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        btnEliminarProvedor.setText("Eliminar Provedor");
        btnEliminarProvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProvedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        btnModCompra.setText("Modificar Compra");
        btnModCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCompraActionPerformed(evt);
            }
        });
        getContentPane().add(btnModCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        btnCrear.setText("Crear Provedor");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        new CrearProvedor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnConsultarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCompraActionPerformed
        // TODO add your handling code here:
        new Consultar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarCompraActionPerformed

    private void btnEliminarProvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProvedorActionPerformed
        // TODO add your handling code here:
        new BorrarProvedor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarProvedorActionPerformed

    private void btnActPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActPrecioActionPerformed
        // TODO add your handling code here:
        new ActualizarPrecio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnActPrecioActionPerformed

    private void btnModCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCompraActionPerformed
        // TODO add your handling code here:
        new ModificarCompra().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnModCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCompraProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCompraProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCompraProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCompraProvedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCompraProvedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActPrecio;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultarCompra;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminarProvedor;
    private javax.swing.JButton btnModCompra;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
